### ISSUE TITLE
SDK not on start.branch.io

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/web-branch-deep-linking#237]
https://start.branch.io/#/integrate-sdk/steps

No tab for the web :-1:

**Comment by h15ter** [comment]
+1

**Comment by SleeplessByte** [comment]
This is still the case.

**Comment by jsaleigh** [comment]
Thanks for the feedback on this! It is definitely appreciated, and has not been ignored.

We're speccing out a project to revamp this entirely, so this will be revisited in that project.  Since that process will be entirely different, I'm closing out this issue.
