### ISSUE TITLE
Web install quide errors and missing information

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/web-branch-deep-linking#238]
[Configuring your Web App](https://dev.branch.io/recipes/quickstart_guide/web/#configuring-your-web-app): No Information provided
[Installing the SDK files](https://dev.branch.io/recipes/quickstart_guide/web/#installing-the-sdk-files): No information provided.
[Quick install web SDK](https://dev.branch.io/recipes/quickstart_guide/web/#quick-install-web-sdk): code block is broken and *Manual installation* doesn't actually tell you how to install.

[Initialization and Event handling](https://dev.branch.io/recipes/quickstart_guide/web/#initialization-and-event-handling): The web is not freaking cordova/phonegap crap. There is no such thing as a `deviceready` or `resume`event.

[Tracking Content Views](https://dev.branch.io/recipes/quickstart_guide/web/#tracking-content-views)
"Just add this one line": no line provided

The actual information that does explain something is under [Mobile Web Smart Banner](https://dev.branch.io/recipes/quickstart_guide/web/#mobile-web-smart-banner)

**Comment by dmitrig01** [comment]
hey @SleeplessByte, thanks for bringing these things to our attention. it's definitely a mess right now - we need to fix this. I appreciate your persistence in working through things, and holding us to a higher standard, as always!!

**Comment by SleeplessByte** [comment]
:+1: I know how to traverse the repo, but I would suspect new, less familiar users don't

**Comment by zeeshabnc** [comment]
@SleeplessByte Thank you for your feedback and apologies for not closing this out earlier. We have made a lot of improvements since then, closing this issue out for now.
