### ISSUE TITLE
Banner is too small on mobile devices

### ISSUE THREAD

**Issue by litalhassine** [BranchMetrics/web-branch-deep-linking#262]
Hi,

When using branch.io smart banner the banner is too small on mobile devices like iphone 6 or 5, espicially in portrait mode.
Using view port is not an option for me because that would affect the whole page and not just the banner.

In order to increase the banner size I had to do it manually with css on every element in the banner.
For example:
branch.banner({
        icon: 'myicon.png',
        title: 'My App',
        description: 'My app description',
        openAppButtonText: "START",
        downloadAppButtonText: "START",
        rating: 5,
        reviewCount: 500,
        showAndroid: false,
        showDesktop: false,
        mobileSticky: true,
        forgetHide: false,
        iframe: true,
        customCSS: '.title { padding-top: 20px; font-size:2vw} #branch-banner .icon img {width: 60vh; height: auto !important} #branch-mobile-action,#branch-mobile-action {background-color: #43CC80 !important; border: none !important; border-radius:5px !important; color: white !important; font-weight:bold !important; font-size:3.5vw !important; margin-left: -4vw !important}',
    }, {
        data: {
            'custom': 'custom',
            'pageUrl': pageUrl,
            '$always_deeplink' : false,
        }
    });
And also - 
 var bannerDidShowListener = function(event) {
        $($('#branch-banner-iframe').contents().find('style')).append('.title {font-size:3vw !important} .description{font-size:2vw !important} #branch-banner {box-shadow: 0 0 20px rgba(0, 0, 0, .35)} #branch-banner .content {height:75vh !important}');
        $('#branch-banner-iframe').attr('style',$('#branch-banner-iframe').attr('style')+' height:auto !important; box-shadow: 0 0 0');
    };
branch.addListener("didShowBanner",bannerDidShowListener);

I would like to able to control the banner size and have the elements in the banner grow if there is enough space for it.

**Comment by jsaleigh** [comment]
Hey @litalhassine!  I can see the issue you're talking about with the viewport meta tag, but I'm afraid it may be some time before we can implement the full level of customization that it sounds like you would want. However, it's great seeing you making use of the customCSS field...this is exactly the case we put it in for :)

What I'm curious about is what the need is for the separate style adjustments, outside of the customCSS field? Is that something that didn't work while it was in the field?

**Comment by litalhassine** [comment]
Hi @jsaleigh !
Thanks for your response, I hope you will get to viewport meta tag soon. I would love to give it a try we you do! 
Using your smart banner on mobile is our main use case since we want to drive installs for our apps on mobile. And comparing to the apple banner the branch banner is very small on mobile devices like iphone and we believe that is the reason it drives less conversions.

About the custom css - yes, it does not work :-( 
For example, I want to increase the banner title size to match the now bigger banner.
If i add to the custom css ".title {font-size:3vw !important}" the title remains small.
Only adding it in the bannerDidShowListener solved the problem and changed the title size.
If you would like I can send you the link to the page and the code in private. You can reach me at lital at joytunes dot com.

Thanks again for your response, rock on.

**Comment by h15ter** [comment]
Hi @jsaleigh !
I had a chance to try smart banner web sdk yesterday, and I also feel it's pretty weird to override every single style inline from js code rather than load custom css. There should be the default css file, and the ability to load and apply a custom one on top of it. I can hack it in frameless mode, but with iframe it becomes more tricky and fragile.

**Comment by jsaleigh** [comment]
@h15ter I totally agree. We're actively working on some changes to help with this right now, and hope to have some releases very soon.

**Comment by jsaleigh** [comment]
With the latest addition of Journeys in the Branch Dashboard, all of these cases should now be handled.  Closing this issue.
