### ISSUE TITLE
Clicking '#branch-mobile-action' refreshes SPA when banner is iframe

### ISSUE THREAD

**Issue by mrblueblue** [BranchMetrics/web-branch-deep-linking#277]
https://github.com/mrblueblue/branch-iframe-test

When the banner is an iframe, the clicking the "branch-mobile-action" `<a/>` will refresh a Backbone application when:
1. The mobile action `href` is set to "#" and its `target` is set to "_parent"
2. The banner iframe `src` is set to "about:blank"
3. The Backbone application has made at least one route change, giving `history` a state

I don't fully understand the dynamics of number three: the refresh does not happen when you are on the first application route. 

Clicking the mobile action on the first route will just append a '#' to the route name, but on subsequent routes, a page refresh is triggered because the route is set to '/#' which is the root of the application.

This refresh behavior goes away when you:
1. Don't use an iframe; or,
2. Delete the `href` attribute of the mobile action; or, 
3. Delete the `target` attribute of the mobile action

Please let me know if this is the expected behavior of the iframe banner for single page applications.

For now,  I will just use the non-iframe banner.

**Comment by GentryRiggen** [comment]
For my project, I have to use the iFrame. Having the href in a link is usually to get the automatic cursor: pointer from the browser on hover. There is no hover in mobile. DELETE THE href. Please :)

**Comment by GentryRiggen** [comment]
My last comment wasn't helpful. This one is for those of you that have to use the iframe.

`var didShowBannerListener = function () {
					var iframe = document.getElementById("branch-banner-iframe");
					var iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
					iframeDocument.getElementById('branch-mobile-action').removeAttribute('href');
				};
				
				branch.addListener('didShowBanner', didShowBannerListener);`

**Comment by rubinsingh** [comment]
Hey Everyone,

Our Product and Technical teams have decided to not move forward with this feature request. Reason being that the WebSDK depends on information from the browser for most of our SDK features. We lose that information if it runs server-side instead.

We apologize for any inconveniences caused as a result of this decision and we look forward to servicing your needs through the browser environment.

**Comment by rubinsingh** [comment]
Hey Everyone,

Our Technical teams have decided to not move forward with this feature request. Reason being that the Smart Banner has been replaced with Journeys. The 'branch-mobile-action' element in a comparable Journeys banner is a div and not an anchor tag with a '#' href. For this reason, I highly advise using a Journeys banner instead. Please email integrations@branch.io for further troubleshooting.
