### ISSUE TITLE
Button colour cannot be changed

### ISSUE THREAD

**Issue by huangjun604** [BranchMetrics/web-branch-deep-linking#314]
I try to change the button color in android.

**Both**

`customCSS: '.button { background-color: #2868be;}'`

**And**

`buttonBackgroundColor: '#2868be', `

are not working. What's the problem? Thanks

**Comment by jeanmw** [comment]
Hi Huang, Can you try this for customCSS instead?
`customCSS: '#sms-form #branch-sms-send {color: blue; background-color: yellow;}',`

**Comment by zanemcca** [comment]
I am experiencing this as well and it appears to be an obfuscation error. 

The options are transferred to another object [here](https://github.com/BranchMetrics/smart-app-banner-branch-deep-linking-web-library/blob/3986cbfd1d71721c7a5bce05ae43b9030d1bd7a1/dist/build.js##L1813-L1818) which then gets accessed [here](https://github.com/BranchMetrics/smart-app-banner-branch-deep-linking-web-library/blob/3986cbfd1d71721c7a5bce05ae43b9030d1bd7a1/dist/build.js#L1276-L1302). Unfortunately the obfuscated code changes the name of the variable in the first transfer but not in the second access. This results in the variables being read as `undefined` and then they end up using their default values.

**Comment by jsaleigh** [comment]
Hey @zanemcca, thanks for finding that.  We'll try to get a fix for that in a build as soon as we can, but I'm afraid I don't have a timeline for it just yet.

**Comment by jgrasl** [comment]
Hi, I was able to set the color of the button using the #branch-banner.

`customCSS: '#branch-banner .button {background-color: blue; border-bottom: blue;} #branch-banner .button:hover {background-color: white; border: 1px solid blue}',`

**Comment by zeeshabnc** [comment]
Hi @jgrasl. I am glad you found a work around for this issue. I am going to close this issue out for now, but feel free to open it up if you are still facing an issue.
