### ISSUE TITLE
App Smart Banner: Sticky banner does not work when iframe is set to false

### ISSUE THREAD

**Issue by mattmcneeney** [BranchMetrics/web-branch-deep-linking#316]
When initialising the app smart banner with

`banner.banner({ /* options */ }, { /* data */ })`

setting the option `mobileSticky: true` (to change the banner from `position: absolute` to `position: fixed` does not work when setting the option `iframe: false`.

I've added a manual style override for now, but it is probably worth fixing this or at least adding a note to the documentation.

**Comment by jsaleigh** [comment]
Thanks @mattmcneeney, I'm taking a look at this now and hope to have a solve in one of the next few updates

**Comment by zeeshabnc** [comment]
Hi  @mattmcneeney, thank you for bringing this to our attention. As I understand, this is something you have worked around by manually overriding the style. For now, we do recommend using the iFrame option with mobile sticky. I am closing this issue out for now, but we will update the documentation accordingly.
