### ISSUE TITLE
Branch SDK initialization failed, so further methods cannot be called

### ISSUE THREAD

**Issue by jamesfzhang** [BranchMetrics/web-branch-deep-linking#321]
I'm seeing this error from users on Firefox 45 on Mac & Windows.

```
Error: Branch SDK initialization failed, so further methods cannot be called
File https://cdn.branch.io/branch-latest.min.js line 59 col 506 in U/</<
File https://cdn.branch.io/branch-latest.min.js line 5 col 348 in b
File https://cdn.branch.io/branch-latest.min.js line 5 col 374 in b/<
File https://cdn.branch.io/branch-latest.min.js line 59 col 344 in l
File https://cdn.branch.io/branch-latest.min.js line 64 col 462 in d
File https://cdn.branch.io/branch-latest.min.js line 66 col 35 in V.prototype.init</<
File https://cdn.branch.io/branch-latest.min.js line 61 col 461 in W/<
File https://cdn.branch.io/branch-latest.min.js line 31 col 259 in Da/q
9 File https://cdn.branch.io/branch-latest.min.js line 27 col 214 in Ba/g<
```

**Comment by reintroducing** [comment]
We're seeing this error a ton in our Sentry logs as well. Any updates on this?

**Comment by jsaleigh** [comment]
@jamesfzhang @reintroducing do you have some live examples where this is happening by chance? We've been unable to reproduce it locally so far.

**Comment by jamesfzhang** [comment]
@jsaleigh Scratch what I said about Firefox 45 only, I see the same error on IE as well. Here are some URLs:

https://theartistunion.com/tracks/b30ef4
https://theartistunion.com/tracks/322ca1
https://theartistunion.com/tracks/357de1
<img width="849" alt="screen shot 2016-04-25 at 9 22 19 am" src="https://cloud.githubusercontent.com/assets/2057670/14790762/9dd13aa6-0ac7-11e6-8107-2595fec8b3f3.png">

**Comment by reintroducing** [comment]
The URLs for us seem to happen randomly on www.spothero.com.  I'm looking at Sentry to gather errors on our production environment.  Here is another interesting issue which may or may not be related: 

https://www.dropbox.com/s/legrip7w08mk4l8/Screenshot%202016-04-25%2011.31.35.png?dl=0

Here is one of the line items for this error, though looking at the logs of the past 24 hours I see 3 separate ones.

https://www.dropbox.com/s/fb2jrd22rscby2e/Screenshot%202016-04-25%2011.38.40.png?dl=0

**Comment by jsaleigh** [comment]
Very helpful, thank you both! We're taking a look at this right now to get this working for you

**Comment by juansalas** [comment]
Thanks @jsaleigh ! Any updates on this issue. We are also seeing a lot of **Branch SDK initialization failed, so further methods cannot be called** errors as well.

**Comment by jsaleigh** [comment]
@juansalas I believe most of the cases we've seen have been dealt with, but if you're seeing it on your site I would definitely want to take a look.  Do you have a live link by chance?

**Comment by samonderous** [comment]
We get tons of these: https://www.instawork.com/jobs. Not sure if this will help. I can send more.

Windows 10
Chrome Version: 51.0.2704

Error
Branch SDK initialization failed, so further methods cannot be called
/branch-latest.min.js in Array.<anonymous> at line 64:506
c=c||document.body;d=document.createElement("div");d.id="branch-banner-container";d.className="branch-animation";d.innerHTML=b;d.querySelect {snip}
function S(b,a,c,d,e){function g(){O(f.querySelector("#branch-banner"),"branch-animation-out");P(f.querySelector("#branch-banner"),"branch-a {snip}
g()})});var c=b.querySelectorAll(".branch-banner-continue");Array.prototype.forEach.call(c,function(a){a.addEventListener("click",function() {snip}
document.createElement("div");m.id="branch-banner";document.body.insertBefore(m,null);O(m,"branch-banner-is-active");if(!d.get("hideBanner", {snip}
!0)}}};var T;
{snip} ed outside of the queue order")),null);if(2===d.g)return l(Error(w("Branch SDK initialization failed, so further methods cannot be called")) {snip}

**Comment by aaustin** [comment]
Hey @samonderous - Thanks so much for the data. We'll be investigating more potential browser edge cases this week. Stay tuned to this thread for more updates.

**Comment by jsaleigh** [comment]
Hi @samonderous - Thanks for the link.  I tried it locally, and it appears to be working from here, so the next step is to figure out why the initialization isn't working where you are.  There are a few possibilities we'll look into.

While we're looking into that, can you check to see if you can hit this link from your location: https://k0dt.app.link/ntEgy16BRv

You should get a basic 404 page that says only 'File not found.'  If you see anything else, or do not have only that exact text on the page, that might be a clue.

That page is on a server that needs to be accessible to initialize the SDK.  If you can't reach it for any reason, that could cause the issue.  We want to keep that server available to any of your users, so if you cannot see it, they might not be able to either.

Please let me know what you find, and thanks in advance!

**Comment by samonderous** [comment]
I see "File not found." so I guess your server is being reached.

**Comment by jsaleigh** [comment]
Cool, that's very helpful info.  It definitely narrows the scope of the problem down.  Thanks :)

**Comment by jsaleigh** [comment]
Quick feedback: we haven't been able to repeat, or find any specific causes of these issues yet.  We do have a PR available that adds a bit more information when initialization fails, that needs to go through QA before we can deploy it:

https://github.com/BranchMetrics/web-branch-deep-linking/pull/365

**Comment by jsaleigh** [comment]
Hey all...the observability changes have been deployed today.  If there are issues with initialization, there should now be just a bit more information available.  If you are still having issues, and see helpful information in your logs, please post it :)

Thanks!

**Comment by kevinhylant** [comment]
@jsaleigh I am also seeing `File not found` when trying the link you provided above.
At classpass.com, we are seeing >1000 of errors per day across all browsers, with IE11 being most prevalent (despite being a relatively small percentage of our userbase)

![image](https://cloud.githubusercontent.com/assets/7389576/17892703/9f717a54-6910-11e6-831a-0e6239bb6ebe.png)

**Comment by jsaleigh** [comment]
Hey @kevinhylant, it looks like you have a slightly older version of the web sdk bundled into your vendor.js file.  The current version (2.7.0) has a bit more information on why an initialization can fail, along with a few tweaks that may help.

We're looking for any insight into what is actually causing the `branch.init()` failures in these browsers, so anything you can help with would be greatly appreciated :)

**Comment by kevinhylant** [comment]
@jsaleigh  - With the updated SDK, the error I'm seeing is the following. Hope that is helpful!
`Branch SDK initialization failed, so further methods cannot be called
 Failure Code:Error in API: 429`

**Comment by jsaleigh** [comment]
Hey @kevinhylant, sorry for the delay, I wanted to make sure I was giving you accurate information.

First off: Thank you! That snippet was very helpful. Since we haven't seen these errors in-house, feedback like yours is what helps us build the best experience for your users.

We've made some changes that should help reduce and possibly eliminate that specific error.  If you continue to see it frequently, or see any other errors, please post them here.  I'm going to keep this issue open for a bit, just in case any new errors surface with the new observability code.

**Comment by kevinhylant** [comment]
Thanks! I'll keep an eye on it - I just took a look at TrackJS (the tool we use for production JS error tracking) and have seen that the # of errors have dropped and that the most common error reason had to do with `adblock` which seems to make sense - though if the users had Adblock turned on, wouldn't the Branch web SDK not load at all?

- Either way, thanks for the help & I'll keep an eye on it

**Comment by jsaleigh** [comment]
Yes, if AdBlock is turned on, the web SDK might not load.  And if it did load, it would not initialize, which should cause all subsequent calls to fail silently, with only a console message saying that the SDK was not initialized.

That said, since you are seeing errors with AdBlock, we'll get the team to look into that, just in case we've missed something.

**Comment by kevinhylant** [comment]
@jsaleigh - Potentially not initialization related, but seeing this error trending.. 1,683 times in 14 days for 1,216 unique users...

![image](https://cloud.githubusercontent.com/assets/7389576/18208966/ad24369a-70ff-11e6-8309-388956a11152.png)

Also, still having **a lot** of errors with initialization... seems intermittent (time-wise)
![image](https://cloud.githubusercontent.com/assets/7389576/18209018/eff356cc-70ff-11e6-87d0-a12d7d92ad7f.png)

**Comment by kevinhylant** [comment]
@jsaleigh ^^ Still seeing high levels of errors

**Comment by jsaleigh** [comment]
Hey @kevinhylant, this is really helpful knowledge.  Would you be open to direct communications with our infrastructure team?  We've been discussing your case, and are very interested in squashing the issues you're seeing.  If you're willing, please open a ticket here https://support.branch.io/support/tickets/new and mention my name.  I'm letting the integrations team know that you might be pinging them so that it would be forwarded to myself and our engineering team.

**Comment by kevinhylant** [comment]
@jsaleigh  Just created the ticket! Look forward to fixing this

**Comment by aaustin** [comment]
Hey team - We're removing that JS error in https://github.com/BranchMetrics/web-branch-deep-linking/pull/378. From now on, errors will only be passed to the [callback](https://github.com/BranchMetrics/web-branch-deep-linking#callback-format), so that you can handle appropriately. These types of init errors can be introduced by all sorts of mobile network and desktop things as networks are never perfect. We suggest you add appropriate failure handling as needed by your feature

Apologies that there's no universal fix here!
