### ISSUE TITLE
Always show banner

### ISSUE THREAD

**Issue by nitrag** [BranchMetrics/web-branch-deep-linking#338]
I have a particular page where I want the banner to ALWAYS display regardless of the user already having the app installed. During testing, it seems that it does not show the banner if the user has already clicked or installed.

Eg. I have product pages. If a user has the app installed but someone sends them a product link from the web, I still want the page to show the banner - "See this product in the App".

**Comment by nitrag** [comment]
Perhaps?

https://github.com/BranchMetrics/web-branch-deep-linking/pull/339

**Comment by zeeshabnc** [comment]
Hi @nitrag, Are you still facing an issue here? We do not hide the banner if the user has the app installed. If you are still seeing this issue, can you send us over a link to the site that has the banner so we can take a look at the configuration. Also, you can set the forgetHide=true to always show the banner even if a user has dismissed it.

**Comment by nitrag** [comment]
Sorry I found the solution, it was related to not using all the properties I think. Closing, sorry for leaving open.

**Comment by zeeshabnc** [comment]
No worries, thank you.
