### ISSUE TITLE
XMLHttpRequest cannot load https://api.branch.io/v1/open

### ISSUE THREAD

**Issue by alexisrogermazarine** [BranchMetrics/web-branch-deep-linking#343]
Hello there, 

I'm working with deepviews, just making my app opening directly from my mobile website (open_app to true), and passing some datas through it.
I have an error XMLHttpRequest cannot load https://api.branch.io/v1/open. Origin [MYDOMAIN] is not allowed by Access-Control-Allow-Origin.

I have an htpasswd but I don't know if it has something to do with it.

**Comment by jsaleigh** [comment]
Hi @alexisrogermazarine. That's definitely an add one.  The API call should be returning an `Access-Control-Allow-Origin` header for you, with a value of `*`.  That should be enough to let the browser know that your site is allowed access to the API call, but it sounds like you're seeing something different.

Do you have the setup needed to view the request and response headers for the API call?  That might help to see what is going on.

Also, what type of device and browser are you seeing this on?  Just in case there are some misbehaviors in our API based on that.

**Comment by aaustin** [comment]
Also, sometimes, we've had issues with excessively restrictive security policies. You might need to add us to your content security policy: https://dev.branch.io/features/website-to-app-routing/support/#calls-to-branchdomain-blocked

**Comment by alexisrogermazarine** [comment]
@jsaleigh Thanks for your answer. 
I only load the Branch SDK in the header. What is weird is it has been working when I tested it on Safari iOS 8.4. I'm now testing on Safari iOS 9.3.2 since I updated my iPhone 6 Plus.

@aaustin Thanks for your reply.
I tried to do so, but I may have misunderstood something. If add CSP meta tag, and default-src to my branch subdomain (which is different from the domain of my mobile website) all of my images, js, css are blocked due to security properties. So I tried to set connect-src only but others calls of APIs are blocked too. That's why I don't know how to deal with this meta tag..

**Comment by jsaleigh** [comment]
@alexisrogermazarine Do you have a live version of your page by chance? I might be able to see something internally that could be causing this

**Comment by alexisrogermazarine** [comment]
@jsaleigh I'm sorry but don't have any live version right now.. Instead, I can send you an extract of header which is returning me a 400 Bad Request.

**Comment by zeeshabnc** [comment]
@alexisrogermazarine Are you still facing an issue with this?

**Comment by alexisrogermazarine** [comment]
@zeeshabnc This one particulary is not an issue anymore. But opening the app automatically didn't work, so I decided to open it via a click on a CTA, which seems to work way better.

**Comment by aaustin** [comment]
@alexisrogermazarine That should definitely work. If you want to invest in a fix. Can you send a note to integrations@branch.io with some more details about your app? We'll help you figure out the config issue.
