### ISSUE TITLE
sendSMS() creates new link eventho option is set to false

### ISSUE THREAD

**Issue by JStammen** [BranchMetrics/web-branch-deep-linking#361]
We at Wazzurb have created an own Text me the App page. 

It was made for this part of the story: 
1. User A invites User B trough email. (example link: wazzurb-test.link/AbhDeeR)
2. User B opens the link on desktop and gets redirected to the Text me the app page
3. User B fills in his phonenumber and recieves an sms
4. User B clicks the link in sms and installs

The problem starts when the link from the email differs from the texted link eventho we use the setting create new link to false

Heres a snippet from the page:
`function sendSMS(form) {
            var formvalue = form.phone.value;
            var result = formvalue.substring(1);
            var phone = "+31" + result;
            var linkData = {
                data: {
                    $og_app_id: "397925937067986",
                    $og_description:"Wazzurb; jouw buurt in een veilig Nederlands sociaal netwerk",
                    $og_image_url:"https://api.wazzurb.com/bitbucket/wazzurb/weekly/wazzurb.png",
                    $og_title:"Wazzurb"
                }
            };            
            var options = { make_new_link: false };
            var callback = function(err, result) {
                if (err) {
                  document.getElementById("alert-danger").style.display = 'block';
                  document.getElementById("alert-success").style.display = 'none';
                } else {
                  document.getElementById("alert-success").style.display = 'block';
                  document.getElementById("alert-danger").style.display = 'none';
                }
            };
            branch.sendSMS(phone, linkData, options, callback);
            form.phone.value = "";
        }`

**Comment by jsaleigh** [comment]
Hi @JStammen!  I have a question about this, is the data being passed through the link to your app the same between the two different scenarios?

The reason I ask, is even with 'Create New Link' set to false, you would still get a new URL in some circumstances.  The actual 'Link' itself, though, would remain the same.  This is the data you see in the dashboard, and references the data that you are passing through.

So if the data is different throughout the user story you outlined, there is something to look into.  But if the data is the same, even with different URLs, then that is expected functionality.

**Comment by JStammen** [comment]
Hi @jsaleigh! 
The data in the scenario's stays the same the only thing that changes is the link. 
But we would like for the link to remain the same. Since when we create the link that gets send trough email we safe the referral link with some other data. 
And when that user installs we check if that link exists but when the link differs like what happens with the text me the app page we cant connect user A with user B.
So if thats expected functionality we shouldnt safe the referral link and find another way to make sure we could connect user A with user B right?

**Comment by jsaleigh** [comment]
Hey @JStammen, I got some feedback from the Integrations team, and it seems that the user_id might be the best option for your use case.  Hope this helps!

If you have any questions, our Integrations team is really awesome, and will likely have better answers than me: https://support.branch.io/support/home

Closing this out since things seem to be working as expected :)

**Comment by JStammen** [comment]
Hey @jsaleigh, we managed to make things work! Thanks for the help and whenever we got some other questions well ask the integrations team :)
