### ISSUE TITLE
Incorrect text in button

### ISSUE THREAD

**Issue by jaybekster** [BranchMetrics/web-branch-deep-linking#363]
Hello.
I always see Install text in button and it changes to Open only after I open installed application.
How to make banner showing the Open text if the appropriate application has been installed?

**Comment by jsaleigh** [comment]
Hi @jaybekster!  There isn't really a way for the Web SDK to know that a user has the app installed from a web page, until that user opens the app with the native SDK (iOS / Android / etc) at least once.

If you have any questions about this functionality, our Integrations team is top-notch, and can help out better than I could:  https://support.branch.io/helpdesk
