### ISSUE TITLE
SendSMS not working

### ISSUE THREAD

**Issue by emilioicai** [BranchMetrics/web-branch-deep-linking#366]
I'm trying to call the `.sendSMS()` method but all I get is an error back with little description.

This is what I do:

```
branch.init('key_test_mykeygoeshere');
branch.sendSMS("0031645159778", {
	tags: ["tag1", "tag2"],
	channel: "facebook",
	feature: "dashboard",
	stage: "new user",
	data: {
		mydata: "something",
		foo: "bar",
		$desktop_url: "http://myappwebsite.com",
		$ios_url: "http://myappwebsite.com/ios",
		$ipad_url: "http://myappwebsite.com/ipad",
		$android_url: "http://myappwebsite.com/android",
		$og_app_id: "12345",
		$og_title: "My App",
		$og_description: "My app's description.",
		$og_image_url: "http://myappwebsite.com/image.png"
	}
}, {}, function(err, res) {
	console.log(err, res)
})
```

and this is what I get in my callback:
```
Error: Error in API: 500
    at Error (native)
    at XMLHttpRequest.Ja.f.onreadystatechange (https://cdn.branch.io/branch-latest.min.js:30:81)
    at XMLHttpRequest.nrWrapper (https://www.deskbookers.com/en-gb/book/step5?tsbt=1&reference=&pid=55403:34:11451) undefined
```
![screenshot 2016-08-19 at 11 38 04](https://cloud.githubusercontent.com/assets/807710/17805918/18e8ce76-6602-11e6-8cb8-1697576345e9.png)

Other methods like `.track()` or `.link()` seem to work fine

**Comment by yntema** [comment]
Hi @emilioicai, can you confirm that you are still receiving this error? Are you able to reproduce consistently? Thanks!

**Comment by zeeshabnc** [comment]
Closing this out since we haven't heard back. @emilioicai Feel free to reopen if you are still facing an issue.

**Comment by sharma-ak** [comment]
I'm also getting the same issue, while trying to send an sms to a mobile number. Getting the same issue https://cdn.branch.io/example.html here as well
<img width="434" alt="Screenshot 2022-09-29 at 10 31 14 AM" src="https://user-images.githubusercontent.com/87856780/192942963-c1241916-
<img width="448" alt="Screenshot 2022-09-29 at 10 31 57 AM" src="https://user-images.githubusercontent.com/87856780/192943057-75647f7a-9370-4036-ba9c-a5520cf2d886.png">
03eb-4bcf-b68e-e59c5f239840.png">

**Comment by jf-branch** [comment]
Hi @sharma-ak, you are seeing this because we have migrated away from SMS to support QR Codes given the greater conversion rates. You can read up on migration options here: https://help.branch.io/using-branch/page/tmta-migration
