### ISSUE TITLE
WebStorage issue

### ISSUE THREAD

**Issue by b12031106** [BranchMetrics/web-branch-deep-linking#388]
Hello,

We are using TrackJS on our website to track errors, and we've found 2 issues:

`Cannot read property 'setItem' of null`

`Cannot call method 'setItem' of null`

From looking at the stack trace, I believe the following is causing the issue:

https://github.com/BranchMetrics/web-branch-deep-linking/blob/master/src/2_storage.js#L95

The isEnabled method for WebStorage only checks sessionStorage, but doesn't check whether localStorage works or not.
We've found that just because sessionStorage works doesn't mean that localStorage will work, and is why this error keeps popping up.

Please help us fix this issue.

Thanks in advanced.

**Comment by jsaleigh** [comment]
Thank you @b12031106, great catch. We're looking into it now.

**Comment by zeeshabnc** [comment]
@b12031106 Can you upgrade to the latest WebSDK version (v2.11.0) and give this a try. We put in a fix to address this. Closing this for now, please re-open it if you still encounter any issues.
