### ISSUE TITLE
Avoid eval for Rollup.js

### ISSUE THREAD

**Issue by Gp2mv3** [BranchMetrics/web-branch-deep-linking#393]
Hi guys,
I'm currently using the branch-sdk with rollup.js but I get the following error:

> rollup: Use of `eval` (in /home/gp2mv3/www/covevent/refonte2/ionic/node_modules/branch-sdk/dist/build.min.js) is strongly discouraged, as it poses security risks and may cause issues with minification. 
> See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details 

Why is eval used ? Isn't there other solutions ?

**Comment by yntema** [comment]
@Gp2mv3, thanks for bringing this to our attention. We aren't using eval in any of the source code, but it does get introduced by the google closure compiler during build. Is this something that is blocking you from using the sdk, or is it just a warning?

**Comment by Gp2mv3** [comment]
It's just a warning but it can discourage people to use the SDK as it warns for security.                                                                                                                                                                                                                                                                                                                   De: notifications@github.comEnvoyé: 31 octobre 2016 2:12 AMÀ: web-branch-deep-linking@noreply.github.comRépondre à: reply@reply.github.comCc: nicolascognaux@gmail.com; mention@noreply.github.comObjet: Re: [BranchMetrics/web-branch-deep-linking] Avoid eval for Rollup.js (#393)  @Gp2mv3, thanks for bringing this to our attention. We aren't using eval in any of the source code, but it does get introduced by the google closure compiler during build. Is this something that is blocking you from using the sdk, or is it just a warning?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yntema** [comment]
@Gp2mv3 after looking into it a little more, we determined that this is most likely caused by using JSON.parse in a couple of locations. We have a safejson.parse method that should be used instead. We will do some testing and hopefully get this fixed in the next deploy. Thanks for notifying us on this!

**Comment by Gp2mv3** [comment]
Guys you're awesome ! Your customer service and relation with developers are really cool. :wink:

**Comment by yntema** [comment]
Thanks @Gp2mv3! I'll let the team know

**Comment by zeeshabnc** [comment]
Hi @Gp2mv3, We believe this issue should be resolved with our latest WebSDK release (v2.12.0). Can you update and let us know if you still see an issue. I will close this out for now, but it would be great if you can update to latest and let us know if it is resolved or you still face an issue.

**Comment by Gp2mv3** [comment]
I updated to 2.12.0 but still get the warning: 
```
[17:46:48]  rollup: Use of `eval` (in 
            /home/gp2mv3/www/covevent/refonte2/ionic/node_modules/branch-sdk/dist/build.min.js) is strongly discouraged, 
            as it poses security risks and may cause issues with minification. See 
            https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details 
```

**Comment by yntema** [comment]
@Gp2mv3 thanks for working with us on this. I think we need to remove any reference to the closure compilers json file. I'll keep you posted.

**Comment by yntema** [comment]
Eval was removed as a dependency in newer versions, please reopen if you find that this isn't the case
