### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by SinisaG** [BranchMetrics/web-branch-deep-linking#395]
Hi guys, 

just want a report a server configuration issue (I don't know where to put this, so I opened a github issue). 
Occasionally, when using Branch web SDK I get  CORS errors. 

Console output (I removed some data from output): 
```
XMLHttpRequest cannot load https://api.branch.io/v1/has-app/MY_KEY?browser_fingerprint_id=xxxxxxxxxxx. The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://localhost:9000' is therefore not allowed access.
```

We've recently went from `v2.1.1` to `v2.11.0`.

Hope you will be able to track down the server responsible. Thanks!

**Comment by jsaleigh** [comment]
Hi @SinisaG!

Thanks for reporting this. Our infra team is looking into the error right now, and hope to have a fix very soon.

**Comment by jsaleigh** [comment]
It looks like the problem was isolated, and has been repaired. If you see this again, please let us know. Thanks again for reporting it :)

**Comment by SinisaG** [comment]
I'll report if I see tho problem again. :) 

Thank you for quick response and action @jsaleigh .

**Comment by jsaleigh** [comment]
Hi @tech-sgsragasagara!  Sorry you're having difficulties with the service. We've done a check against your app id and don't see any errors like this for it over the past several days.  Of course you're seeing the issue, so there must be something going on, and we'll try to help where we can.

Does the problem you're seeing happen very often?  Also do you have a timestamp for when you see the errors?  Any extra information would be great to help us track this down.
