### ISSUE TITLE
can not read parsed data

### ISSUE THREAD

**Issue by holdonnn** [BranchMetrics/web-branch-deep-linking#398]
url created on marketing tab ( https://dashboard.branch.io/marketing ) can be properly read by code.
```javascript
branch.init(key, function (err, data) {
  var parsed = data['data_parsed'];
  ///...
}) 
```
but url created by myself with web-sdk or ios-sdk can not be read 

`parsed`  data from marketing link includes many key, value
but from link i created with sdk have only `+clicked_branch_link:fasle, +is_first_session:true`

i think i properly make link 
here is code for creating my link

```
// branch.init() already call 
branch.link({
        tags,
        campaign,
        channel,
        feature: 'web',
        data: {
          '$deeplink_path': `foo`,
          '$og_title': `foo`,
          '$og_description':'foo',
          '$og_url': 'https://rememberapp.co.kr',
          '$ios_deepview': 'sharebook_deepview',
          '$desktop_url': `https://rememberapp.co.kr/deeplink`,
          '$android_url': `https://play.google.com/store/apps/details?id=kr.co.rememberapp&utm_campaign=${campaign}&utm_source=${channel}&utm_medium=${tags[0]}`,
          '$ios_url': `itms-apps://itunes.apple.com/app/id840553277?pt=41308801ct=${campaign}_${channel}_${tags[0]}&mt=8`,
          '$rmbr_referrer_id': id, // my custom data
        }
      }, function (err, branchLink) {
        console.log(err, branchLink);
      });
```

**Comment by yntema** [comment]
Hi @holdonnn, sorry about the trouble!

I just tried running your code and ran into an error. `'$og_description': foo',` is missing the opening `'` in front of foo. Try that out and let me know if it works :)

**Comment by holdonnn** [comment]
sorry, i had some mistake above example code.
