### ISSUE TITLE
Uncaught TypeError: branch.autoAppIndex is not a function

### ISSUE THREAD

**Issue by czmarcos** [BranchMetrics/web-branch-deep-linking#409]
Got this error using the following code:

```
(function(b,r,a,n,c,h,_,s,d,k){if(!b[n]||!b[n]._q){for(;s<_.length;)c(h,_[s++]);d=r.createElement(a);d.async=1;d.src="https://cdn.branch.io/branch-latest.min.js";k=r.getElementsByTagName(a)[0];k.parentNode.insertBefore(d,k);b[n]=h}})(window,document,"script","branch",function(b,r){b[r]=function(){b._q.push([r,arguments])}},{_q:[],_v:1},"addListener applyCode banner closeBanner creditHistory credits data deepview deepviewCta first getCode init link logout redeem referrals removeListener sendSMS setBranchViewData setIdentity track validateCode".split(" "), 0);

  branch.init('key_live_xxxx');

  branch.autoAppIndex({
    iosAppId:'xxx',
    iosURL:'#/tab/xxx/303',
    androidPackageName:'com.br.xxx',
    androidURL:'#/tab/xxx/303',
    data:{"id":303}
  }, function(err) { console.log(err); });

  branch.deepview(
      {
        'channel': 'mobile_web',
        'feature': 'deepview',
        data : {
          'page_id': 'xxx303',
          '$always_deeplink': true,
          '$deeplink_path': '#/tab/xxx/303/',
          '$fallback_url':'http://www.xxx.com.br/exameple.html',
          '$publicly_indexable':1,
          '$canonical_identifier': 'http://www.xxx.com.br/exameple.html',
          '$desktop_url':'http://www.xxx.com.br/exameple.html',
          '$keywords':['example','branch'],
        }
      },
      {
        'open_app': true,  // If true, Branch attempts to open your app immediately when the page loads. If false, users will need to press a button. Defaults to true
      }
  );

```

Looking at the documentation (https://github.com/BranchMetrics/web-branch-deep-linking and https://dev.branch.io/features/google-app-indexing/advanced/cordova/) it says that the key is named "iosAppStoreId" however in the example it is shown as "iosAppId", don't think that this error is related but I found this error.

Thanks in advance

**Comment by czmarcos** [comment]
---- SOLVED -----
Never mind, solved by including autoAppIndex on the call function:

(function(b,r,a,n,c,h,_,s,d,k){if(!b[n]||!b[n]._q){for(;s<_.length;)c(h,_[s++]);d=r.createElement(a);d.async=1;d.src="https://cdn.branch.io/branch-latest.min.js";k=r.getElementsByTagName(a)[0];k.parentNode.insertBefore(d,k);b[n]=h}})(window,document,"script","branch",function(b,r){b[r]=function(){b._q.push([r,arguments])}},{_q:[],_v:1},"addListener applyCode banner closeBanner creditHistory credits data deepview deepviewCta **autoAppIndex** first getCode init link logout redeem referrals removeListener sendSMS setBranchViewData setIdentity track validateCode".split(" "), 0);


**However I still have this doubt about the different key names iosAppId or iosAppStoreId. Also, which ID is this? How can I exactly find it?**

**Comment by rubinsingh** [comment]
@czmarcos sorry for the confusion. The correct parameter is **iosAppId** and I have updated the documentation over at dev.branch.io with the correct parameter. The github repo's readme file should be updated with the next deploy of the WebSDK.

Also to find your **iosAppId**, please:

1. Copy and paste your app's iTunes URL into a text file
2. Skip to the end of the URL and copy the string of numbers right after **id**

For example, if we look at the iTunes URL for Branch Monster Factory below:

- https://itunes.apple.com/us/app/branch-monster-factory/id**917737838**

The app store id is 917737838.

Hope this helps!

**Comment by czmarcos** [comment]
Thanks @rubinsingh!
