### ISSUE TITLE
Fails to recognise app with window.location.assign

### ISSUE THREAD

**Issue by Muesly** [BranchMetrics/web-branch-deep-linking#412]
I'm trying to open up the app (when user has it installed) from a javascript call in the callback of branch.link()

I'm using window.location.assign(link) but it only opens the fallback URL rather than open the app.  I have also tried window.open(link) and it does the same.

However, a hardcoded <a> link works fine, and opens the app.

Any ideas how I can replicate this in Javascript without hardcoding an <a> link?

**Comment by rubinsingh** [comment]
Hi Muesly,

Apple requires that Universal Links be tapped on directly by the end user. This means that Universal Links cannot be triggered programmatically. 

There are a few other limitations as well:

- Redirecting to a Branch link will prevent it from functioning as a Universal Link
- Wrapping a Branch link for click tracking or any other purpose will prevent it from functioning as a Universal Link

For a complete list, please take a look at: 

- https://support.branch.io/support/solutions/articles/6000153326-ios-universal-links-troubleshooting-guide

**Comment by Muesly** [comment]
Thanks Rubin
