### ISSUE TITLE
Styling for body is not removed after journey close

### ISSUE THREAD

**Issue by actuosus** [BranchMetrics/web-branch-deep-linking#416]
When user closes the journey, styling for iframe and body is not removed from DOM.
Styling is created by appending `<style>` element with id "`branch-iframe-css`" (https://github.com/BranchMetrics/web-branch-deep-linking/blob/master/src/journeys_utils.js#L239) and is not removed from the DOM (document.head) when the journey is closed (https://github.com/BranchMetrics/web-branch-deep-linking/blob/master/src/journeys_utils.js#L452).

**Comment by pavelpower** [comment]
Where is deleted DOM style `branch-iframe-css` ?
https://github.com/BranchMetrics/web-branch-deep-linking/blob/master/src/journeys_utils.js#L240-L242

**Comment by yntema** [comment]
Thanks for catching this. I have a PR to fix this issue that is being review right now and will go out soon: https://github.com/BranchMetrics/web-branch-deep-linking/pull/415

**Comment by yntema** [comment]
This issue has been fixed with the most recent release. I'm going to close this issue. @actuosus @pavelpower , please re-open if you are still experiencing these issues with the latest release. Thanks!
