### ISSUE TITLE
Provide a solution to determine journey visualisation type

### ISSUE THREAD

**Issue by actuosus** [BranchMetrics/web-branch-deep-linking#417]
For specific integration purposes we need to know the visualization for journey banner that will be shown to a user.

The suggestion is to send event metadata to [`willShowJourney`](https://github.com/BranchMetrics/web-branch-deep-linking#available-journey-events) callback.

After some investigation of branch.io API, our team has determined that the following sample configuration is passed to render specific type of the journey banner:
```json
{"bannerHeight":"82px","position":"top","sticky":"fixed","ctaText":{"has_app":"Open","no_app":"Continue"},"injectorSelector":".branch-journeys-top"}
```
This data satisfies our needs.

**Comment by yntema** [comment]
@actuosus , would you mind providing some info on how you might use this? This is more of a feature request, so want to make sure we cover your use cases and those of our other partners.
Thanks, look forward to hearing from you!

**Comment by yntema** [comment]
Closing for now. Feel free to reopen with specific use case information for our product team to consider
