### ISSUE TITLE
Calling Credits Endpoint Fails. Not including branch_key in query string

### ISSUE THREAD

**Issue by zschmid** [BranchMetrics/web-branch-deep-linking#425]
From my testing it looks like the credits() function is not currently working as expected. 
When I make the following call (my app is already initialized and the branch_key is set, other requests work no problem)

```
branch.credits(
    function(err, data) {
       console.log(data);
   }
);
```

This is the response I get when the SDK makes the request to the endpoint:
{code: 400, message: "Invalid or missing app id, Branch key, or secret"}

The request looks like this:
`https://api.branch.io/v1/credits/358367363575727272?browser_fingerprint_id=349675421568588071&identity_id=358367363575727272&sdk=web2.17.0&session_id=358387506509525708
`
Notice that there is no query parameter `branch_key` . 

Reading through the [Web API documentation]( https://github.com/BranchMetrics/branch-deep-linking-public-api#getting-the-credit-history), it seems that this query parameter must be included for the request to succeed. I've verified by manually appending it that the request succeeds. 

I've also looked through the Web SDK tests [/test/3_api.js](https://github.com/BranchMetrics/web-branch-deep-linking/blob/fd7fa91ecce1cb7bc1491560fc72f3a9c1d22e62/test/3_api.js), and it looks like the automated tests are not testing for this query parameter on the credits API call (credits test starts at line ~721), whereas it is testing for it on other functions.

From what I can tell this is a bug, but wanted to start a conversation before submitting a PR just in-case i'm missing something obvious.

**Comment by rubinsingh** [comment]
Hi @zschmid,

Thanks for writing in! I just tested the call to branch.credits() and the call returns with a user's credits correctly. Would you mind sending support@branch.io a snippet that you are testing with? We can continue our conversation through a support case.

Thanks,

Rubin
