### ISSUE TITLE
deeplink data storage problem

### ISSUE THREAD

**Issue by fx69005** [BranchMetrics/web-branch-deep-linking#426]
Hello,
I create Deeplink for share to Facebook in my angular website. works fine !  when i click on facebook link . my website open and i route  user on the good page like this:

```
branch.init(mykey, function(err, data) {
 if (!err) {
         console.log("branche success", data.data_parsed)
          if(data.data_parsed.mydata){
            $state.go("mypage",({'id':data.data_parsed.mydata}))
          }
        } else {
          console.log('erreur Branch : ' , err)
        } 
});
```

but if i close my page and return , Branch.init method keep data informations  and  send user on page:id.
Best regards

**Comment by rubinsingh** [comment]
Hi Chris,

Thanks for writing in! This sounds like an integration issue. We have tried to reproduce it and cannot accurately do so. 

When you write in, if could you provide us with:

1. The Branch Key of your app
2. A video that showcases how you are testing
3. A link that you are testing with

that would be great! Using this information, we will be able to troubleshoot your case and provide you with next steps.

Thanks,

Rubin Singh
