### ISSUE TITLE
data_parsed works for branch.init callback but not for branch.data

### ISSUE THREAD

**Issue by giaset** [BranchMetrics/web-branch-deep-linking#446]
Hi,

In my callback for branch.data(...), I'm getting a null value for data.data_parsed, even though data.data (i.e. the string version) is working fine.

In the callback for branch.init(...), both the data.data_parsed and data.data fields work as expected

Please see attached image:
![screen shot 2017-04-24 at 3 09 20 pm](https://cloud.githubusercontent.com/assets/2816603/25354290/6f121750-2900-11e7-85e6-0db2f45b0a0a.png)

Thanks!

**Comment by jsaleigh** [comment]
@giaset It looks like this issue fell through the cracks, I'm truly sorry about that!  I'll chat with the team about this, and see what we can do to help.

**Comment by rubinsingh** [comment]
Hi @giaset we have a pull request for this issue over at: 

https://github.com/BranchMetrics/web-branch-deep-linking/pull/459

Once reviewed and fully tested, it will be released with the next version of the WebSDK.

**Comment by constantx** [comment]
Still waiting for this fix :) We're hacked around by caching the link id and ignore the subsequent data, but it means user can not visit the same deeplink twice (better than nothing).

**Comment by rubinsingh** [comment]
@giaset @constantx we released v2.24.1 of the WebSDK today! This issue is fixed.
