### ISSUE TITLE
Creating Referral Links

### ISSUE THREAD

**Issue by chiplay** [BranchMetrics/web-branch-deep-linking#452]
I can't find anything in the documentation for how to generate referral links using the web SDK.  Is it as simple as this?

```
branch.link({
  channel: 'referral',
  feature: 'referral',
  data: {
    mydata: 'something',
    '$desktop_url': 'http://localhost:8080',
    '$ios_url': 'http://localhost:8080',
    '$ipad_url': 'http://localhost:8080'
  }
}, function(err, link) {
  console.log(err, link);
});
```

I've tried the above, but I'm not seeing the rewards/referral connection showing up in the dashboard, and when inspecting the `parsed_data` from the generated link, I'm not sure what to look for regarding the referring user's "id".  Any help on how to use the web SDK for referral link creation and proper parsing would be really appreciated!

**Comment by firaskrichi** [comment]
@chiplay did you find a solution? I am running into the same problem.

**Comment by rubinsingh** [comment]
Hey Team,

Apologies for the delay in responding. Here's how you would do it:

1. Set the referring user's identity via a call to setIdentity():

https://github.com/BranchMetrics/web-branch-deep-linking#setidentityidentity-callback

2. Call branch.link() once data from setIdentity()'s callback is present.

3. Grab the generated link and append ?debug=true to it, you should see the "developer identity" attribute filled out with the referring user's name in step 1. This indicates that a referral link was correctly generated.

With regards to debugging why referral rules are not triggering correctly. Please email support@branch.io with your app's Dashboard key and information about the rules that you are trying to trigger.
