### ISSUE TITLE
Add the ability to provide nonce value in a config parameter

### ISSUE THREAD

**Issue by Panya** [BranchMetrics/web-branch-deep-linking#464]
Hi!

We are using branch-sdk on our web app that uses CSP 2 without unsafe-inline (all inline scripts should have `nonce` attribute with valid value). Currently, branch journeys generate inline scripts to redirect the browser to the correct page. And these scripts are not working now (blocked by the browser e.g. Safari 10). I'm wondering, could you add a parameter to provide nonce value and add the `nonce` attribute to the generated scripts?

**Comment by rubinsingh** [comment]
Hey Panya,

Thanks for writing in with your awesome feature request! It has been forwarded to our product team for prioritization. I'll go ahead and close this out for now. Should support for your use-case become available, we'll make a note of it in our [changelog](https://github.com/BranchMetrics/web-branch-deep-linking/blob/master/CHANGELOG.md).

**Comment by kenny26** [comment]
So, any update on this?

**Comment by rubinsingh** [comment]
@Panya @kenny26 and everyone else thank you for your patience. We are actively working on this feature and it will be available in our next deploy most likely by Friday, June 1st.

**Comment by rubinsingh** [comment]
@Panya @kenny26 this feature has been released. You can pass a **nonce** parameter into the options dictionary of branch.init() and it will be added as an attribute to dynamically injected scripts and stylesheets as part of the Journeys flow. For troubleshooting help, please reach out integrations@branch.io.
