### ISSUE TITLE
`link_identifier` should be able to be set from Branch.init options

### ISSUE THREAD

**Issue by samstash** [BranchMetrics/web-branch-deep-linking#469]
`link_identifier` is not sent in the `open` request when the URL is missing an `r` hash or `_branch_match_id` param. This is true even if `branch_match_id` has been set in the Branch.init() options.

The `link_identifier` request parameter should either inherit from the `branch_match_id` option or be available as an option on Branch.init()

### Making a request from www.example.com/?_branch_match_id=12345
`Branch.init(BRANCH_KEY, { branch_match_id: "12345" }, callback);`

```
https://api.branch.io/v1/open
---------------
browser_fingerprint_id: xxxx
branch_key: xxxx
sdk:web2.24.0
options:{"branch_match_id":"12345"}
link_identifier:12345
```

### Making a request from www.example.com/
`Branch.init(BRANCH_KEY, { branch_match_id: "12345" }, callback);`

```
https://api.branch.io/v1/open
---------------
browser_fingerprint_id: xxxx
branch_key: xxxx
sdk:web2.24.0
options:{"branch_match_id":"12345"}
```

**Comment by rubinsingh** [comment]
@samstash thank you for submitting this issue. We have a feature coming out in the next release that will achieve your use-case so I'll go ahead and close this for now.

You'll be able to pass in a branch_match_id to branch.init() like so:

branch.init('<insert_branch_key>', { branch_match_id : '<insert_branch_match_id>' }, initCallback);

Here's the PR for it: https://github.com/BranchMetrics/web-branch-deep-linking/pull/462/files

PS an open request is not made every time - it is made when a branch_match_id present. In the next release you'll be able to pass it in from .init() as well.
