### ISSUE TITLE
User complete action event

### ISSUE THREAD

**Issue by alkesh26** [BranchMetrics/web-branch-deep-linking#472]
We called
```
     branch.track('sign-up', callback)
```
On android and ios sdk's to complete the action we call `userCompleteAction`. Where can we find the same for web-sdk.

**Comment by rubinsingh** [comment]
@alkesh26 if you're trying to trigger a custom event called 'sign-up' from the WebSDK, you are using the correct function for that. branch.track() allows one to fire custom events such as yours from the WebSDK. If you've encountered some issues using it or would like to file a bug, feel free to reach out integrations@branch.io.
