### ISSUE TITLE
Referring Identity is null when parsing branch link url

### ISSUE THREAD

**Issue by mukesh-urbanpiper** [BranchMetrics/web-branch-deep-linking#476]
After creating sharing url with setIdentity() and link() method, the generated url is not containing the `referring_identity` or `identity`. This values are coming as `null`

Steps to reproduce (on https://cdn.branch.io/example.html):
1) init()
2) setIdentity()
3) link()

Click on the generated link.
In Session Info the response doesn't contain the mentioned info (`referring_identity` or `identity`).

**Comment by fearthedear** [comment]
Facing the same issue, did you resolve?

**Comment by mukesh-urbanpiper** [comment]
@fearthedear @mesqfel The issue persists. To make my referral work, I stopped relying  `referring_identity`. Instead I push some additional data (for my case, its unique `user_id`) during init which I am using as identity.

**Comment by mesqfel** [comment]
@mukesh-urbanpiper but how do you pass this additional data to init() ? Because on init() docs there is no key for additional data in the options parameter: https://github.com/BranchMetrics/web-branch-deep-linking#initbranch_key-options-callback

**Comment by mukesh-urbanpiper** [comment]
@mesqfel Hi, you can not push data in `init()` (my mistake). But you can push additional data while creating link. This data will be available when you'll do `init` with the referral link.
**Creating referral link:**
```
branch.init(key, (e, data) => {
	branch.setIdentity(identity, (e, data) => {
		branch.link({			
			data:{
				identity:identity
			}
		}, function(err, link) {
			// handle error
        })
	})
})```

** Extract data from referral link**
```
branch.init(key, (e, data) => {		
	// additional data will be available in the data Obj (i.e. identity). 
        //However referring_identity always comes null
});
```

**Comment by mesqfel** [comment]
Thanks @mukesh-urbanpiper 
Now I understand. But even on this way, it won't automatically trigger the referral rewards rules right. (I've tried here and it didn't triggered the rule, of course...)

To reward the original Referring user I would have to "manually" issue an API POST to /credits endpoint, like here: https://docs.branch.io/pages/apps/api/#referral-reward , passing the parameter identity that I've received from the init() of the referred user.

That's the only way I could thought to reward the Referring user. Did you do the same?

**Comment by mukesh-urbanpiper** [comment]
Yes, I am handling everything in serverside (Manually).

**Comment by mesqfel** [comment]
Ok. Cool!
Thanks a lot @mukesh-urbanpiper !

**Comment by fearthedear** [comment]
Hey @mesqfel & @mukesh-urbanpiper, 

Didn't read through your stuff, but just to leave here how I managed in the end:
on page load I'm doing a `branch.data()` call, which has `result.data_parsed['+clicked_branch_link']` in the callback if the user is coming through a referral link, and `data_parsed` contains the stuff you can save in a branch link created with `branch.link()`, through that I also pass the identity of the referrer.

**Comment by rubinsingh** [comment]
Hey Team,

I'd like to provide a test plan to show that referrals are working correctly.

Here's how I tested:

1. Copy the source from https://cdn.branch.io/example.html -- this is our example WebSDK page, and save it locally to your computer in a folder as an html file.
2. Change the Branch Key in both locations of the file to your app's Branch Key
3. In your app, create some referral rules for the "referred acting user" and "referring user" tied to the event "aaa" in Dashboard.
4. Now go back to the html page and search for the .track function. Change "Tracked this event" to "aaa" and also change the '$desktop_url' in the sampleParams object (you'll have to search for it) to point to your webpage running on your local server ie. http://localhost:8000/referralPage.html
5. When the page loads, populate the textfield next to the .setIdentity() function with "user_a"
6. Push the setIdentity() button
7. Create a link by pushing the .link() button
8. Grab the link that was just created and open a new incognito window
9. Paste the link in the URL bar and then set user's b's identity - follow step 5 and use "user_b"
10. Push the .track() button which will fire "aaa" and trigger the reward rules created in step 3
11. Now go back to the reward rules area in Dashboard and notice that the number of events has increased by 1 for both the referring user and the referred user.
12. If you're interested in viewing whose credits increased, head over to https://branch.dashboard.branch.io/liveview/credits. You'll see "user_a" and "user_b" got credited with certain amounts.

Also, if you're interested in viewing the identity of the user set on the link, please grab the link created in step 7 and append ?debug=true. Once the link resolves to the link debugger page, scroll down to "developer identity" and you should see "user_a" as the owner of the link.

Referring link in link data is null as you've noted so this sounds like a bug. Thanks for reporting but in general, referral rules are working correctly in the WebSDK.

**Comment by rubinsingh** [comment]
We've added the referring_identity null bug to our backlog of issues and we're going to prioritize it internally. If this specific bug is causing major issues for your workflow please let integrations@branch.io and we'll bump the priority. 

Referral rules are working in general based on the previous test plan. Please contact our support team if you have questions about it as it is a complicated process so it's better to troubleshoot through email.

**Comment by rubinsingh** [comment]
I'm going to close this issue out and we'll determine what to do about the referring_identity internally. Thank you for bringing this to our attention once again!
