### ISSUE TITLE
addListener not working

### ISSUE THREAD

**Issue by francorisso** [BranchMetrics/web-branch-deep-linking#529]
The addListener is not working, here is my code:

```
        branch.init(settings.branchIoKey);
        branch.addListener('didShowBanner', () => {
            track('banner.branch.displayed');
        });
        branch.addListener('didDeepviewCTA', () => {
            track('banner.branch.clicked');
        });
        branch.banner({ showAndroid: true, showDesktop: false, showiOS: false, showmobileSticky: true });
```

I even tried to use addListener with a function to log all events, and I'm not getting any events :(

**Comment by francorisso** [comment]
As a comment, this was working two weeks ago.

**Comment by rubinsingh** [comment]
@francorisso sorry for the delay in our responding. For integration related issues integrations@branch.io is the fastest way to contact our team. 

In any case, I did some testing and here's what I found:

1. A listener for the **didShowBanner** event does trigger correctly (see test plan below).
2. **didDeepviewCTA** is not an event that is published in the WebSDK
3. There is currently an outstanding bug when trying to listen for all events. I'm going to work on this shortly.

Test plan for 1:

1. Navigate to https://cdn.branch.io/example.html in Chrome
2. Once you've landed on the page, open up developer console and type in:
    **var listener = function(event) { console.log(event); }**
    then hit return 
3. Keep developer console open and type in: 
    **branch.addListener('didShowBanner', listener);**
    hit return again
4. Finally, push the ".banner" button on the page and you'll see the **didShowBanner** event trigger

I've tried the test above with:

```
branch.addListener('didShowBanner', (event) => {
            console.log('hello');
        });
```

and it works fine as well. Is this still an issue?

**Comment by rubinsingh** [comment]
@francorisso previously there was confusion on my end with **didDeepviewCTA** around whether it worked/or was supported. I just tested it using:

```
branch.addListener('didDeepviewCTA', (event) => {
   alert('hello again');
});
```
in Chrome using a different test page with a Deepview. Once I called, branch.deepviewCta(); from my browser, the alert was thrown correctly. Turns out this is working as well.
