### ISSUE TITLE
Safari 9 `undefined is not an object (evaluating 'window.top.document.referrer')`

### ISSUE THREAD

**Issue by kklimek** [BranchMetrics/web-branch-deep-linking#546]
On Safari 9.1.3 we get error

`undefined is not an object (evaluating 'window.top.document.referrer')`

Seems like it's related to https://github.com/BranchMetrics/web-branch-deep-linking/commit/5c10ccf5f3f8e18b520099a5e8e4e79df52b19e9#diff-7ab92c1898404b32a293ae8501a733f9R1262

**Comment by csalmi-branch** [comment]
@kklimek are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
