### ISSUE TITLE
Storage doesn't handle exceptions at runtime

### ISSUE THREAD

**Issue by brendo** [BranchMetrics/web-branch-deep-linking#584]
We've noticed an increase in errors raised from the `branch-sdk` (v2.28) where the client has `sessionStorage` or `localStorage` available, but exceptions have been raised while getting/setting.

For example:

- [Exception... "SQLite database connection is busy" nsresult: "0x80630001 (NS_ERROR_STORAGE_BUSY)"
- [Exception... "File error: Corrupted" nsresult: "0x8052000b (NS_ERROR_FILE_CORRUPTED)"
- [Exception... "File error: Access denied" nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"
- [Exception... "File error: No device space" nsresult: "0x80520010 (NS_ERROR_FILE_NO_DEVICE_SPACE)" 

A number of browsers/devices appear affected, but Firefox v60 is the most common.

Stacktrace:

```
    webpack:///node_modules/branch-sdk/dist/build.min.js:36:537 r/<
    webpack:///node_modules/branch-sdk/dist/build.min.js:36:489 init
    webpack:///node_modules/branch-sdk/dist/build.min.js:106:382 ./node_modules/branch-sdk/dist/build.min.js/</</kt.prototype.init</</<
    webpack:///node_modules/branch-sdk/dist/build.min.js:100:23 ./node_modules/branch-sdk/dist/build.min.js/</</kt.prototype.c/<
    webpack:///node_modules/branch-sdk/dist/build.min.js:44:208 f
    webpack:///node_modules/branch-sdk/dist/build.min.js:42:400 xe/a.onreadystatechange
```

https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#Testing_for_availability might be a way to better detect storage before attempting to use it?

**Comment by rubinsingh** [comment]
@brendo thanks for writing to us! I tried reproducing the issue via Firefox Quantum v60.0.2 (64-bit) on http://cdn.branch.io/example.html in both private and regular mode and did not see any errors in developer console. Would you mind creating a case by emailing integrations@branch.io and let us know if you've been able to reproduce it? This could be a bug in Firefox: https://stackoverflow.com/questions/18877643/error-in-local-storage-ns-error-file-corrupted-firefox

**Comment by brendo** [comment]
I personally haven't been able to replicate, I noticed it while analysing some Bugsnag reports for the last month or so. FWIW there are also reports from Mobile Safari (v6-8).

I don't think Branch is doing anything wrong per-se, I think the browser is just operating in odd conditions that is throwing unusual errors.

**Comment by csalmi-branch** [comment]
@brendo have you still been seeing these errors lately?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
