### ISSUE TITLE
SendSMS always generate a new link

### ISSUE THREAD

**Issue by marcopesani** [BranchMetrics/web-branch-deep-linking#613]
This is how I initialize branch in page `<head>`:
```
<script type="text/javascript">
  (function (b, r, a, n, c, h, _, s, d, k) { if (!b[n] || !b[n]._q) { for (; s < _.length;)c(h, _[s++]); d = r.createElement(a); d.async = 1; d.src = "https://cdn.branch.io/branch-latest.min.js"; k = r.getElementsByTagName(a)[0]; k.parentNode.insertBefore(d, k); b[n] = h } })(window, document, "script", "branch", function (b, r) { b[r] = function () { b._q.push([r, arguments]) } }, { _q: [], _v: 1 }, "addListener applyCode autoAppIndex banner closeBanner closeJourney creditHistory credits data deepview deepviewCta first getCode init link logout redeem referrals removeListener sendSMS setBranchViewData setIdentity track validateCode trackCommerceEvent logEvent disableTracking getBrowserFingerprintId".split(" "), 0);
  branch.init(branch_key, { no_journeys: true }, function (err, data) {
    if (err) {
      console.error(err);
    } else {
      console.log("Branch initialized", data);
    }
  });
</script>
```

and this is my SMS function, called on phone number form submit:

```
function sendSMS(phoneNumber) {
    branch.sendSMS(phoneNumber, {
      tags: ["SMS"]
    }, {}, function(error, data){
      if (error) console.error(error)
    });
  }
```
**The link send by SMS is always a new link** and we lose the tracking info and the referral attribution

Even trying to debug the branch data with
```
branch.data(function(error, data) {
  console.log(data)
})
```
or
```
branch.first(function(error, data) {
  console.log(data)
})
```
all the referral data is lost.

**Comment by marcopesani** [comment]
Reading the source code, the SDK should be able to automatically identify the existing referral and, if available, use it: https://github.com/BranchMetrics/web-branch-deep-linking/blob/24771e78f6554788f3c1986b8ddfb56437d7f761/src/6_branch.js#L1265

In my specific case, it is not happening. Not only in the sendSms() case, but also in data() and first(): both returns an empty referral.

I'd prefer to not hack how the SDK works, also because I'm not sure how to pass all the internal properties obtained with the initialization payload.

**Comment by marcopesani** [comment]
I created a debug link: https://conio.app.link/github_debug

The destination page prints in the console the init() payload. You can see my problem by typing
`branch.first((err,data)=>{console.log(data)})` in the console

**Comment by marcopesani** [comment]
It didn't work. I tried both with {} and {make_new_link:false}

Do you have a CDN with the SDK not minimized? It can help the debugging

Inviato da iPhone

**Comment by csalmi-branch** [comment]
@marcopesani are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
