### ISSUE TITLE
Latest version broke api.branch.io CSP

### ISSUE THREAD

**Issue by yonilerner** [BranchMetrics/web-branch-deep-linking#627]
The latest version pushed today broke any CSP that relied on api.branch.io, since the API endpoint was changed to api2.branch.io.

- Please provide a way to access older versions of the SDK. Right now, the CDN only offers `latest.min.js`. This is terrible for reliability, since a new version pushed today broke us
- Please announce these breaking changes

Thanks

**Comment by willbooz** [comment]
@yonilerner we're sorry for breaking your CSP, and for failing to announce this change in advance. 

You can access the latest version of our SDK still using api.branch.io here: https://cdn.branch.io/branch-2.47.1.min.js

We're adding instructions for using specific versions of the SDK to our documentation, and we'll work hard to make sure this sort of thing doesn't happen again!
