### ISSUE TITLE
Using Branch SDK on Safari (IOS) when embedded causes SAMEORIGIN error

### ISSUE THREAD

**Issue by jobortunity** [BranchMetrics/web-branch-deep-linking#628]
We use the Branch SDK inside a website which is then embedded by customers. However when initalizing the Branch SDK on our website (within an iframe) we get the following error on Safari (IOS) only: "Blocked a frame with origin 'domain x' from accessing a frame with origin 'domain y'. Protocols, domains and ports must match.". Initializing the Branch SDK on any other browser works perfectly. We've looked inside the branch-latest.min.js code and saw that you use the code "window.top" and this might cause the issue on Safari (IOS) we think.

**Comment by csalmi-branch** [comment]
@jobortunity are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
